language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sunit.kulkarni/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunit.kulkarni/docker-react npm run test -- --coverage
